# https://taskfile.dev

version: '3'

silent: true

# NOTE: these tasks are mostly for testing purposes and
# might not work properly in production. Manually building
# the service with the `go build` command is recommended.

tasks:
  build:
    cmds:
      - go build -o ./bin/gateway{{exeExt}} ./src
  run:
    cmds:
      - task: build
      - ./bin/gateway{{exeExt}} -c tbg.crt -k tbg.key
  buildbot:
    cmds:
      - go build -o ./bin/server{{exeExt}} ./test-server/
  bot1:
    cmds:
      - task: buildbot
      - ./bin/server{{exeExt}} -p 9800
  bot2:
    cmds:
      - task: buildbot
      - ./bin/server{{exeExt}} -p 9801
